version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"